--create database SI2_VLAB
USE SI2_VLAB
GO
CREATE TABLE [dbo].[DEMO](
	[id] [int] NOT NULL,
	[value] [varchar](50) COLLATE Latin1_General_CI_AS NOT NULL,
 CONSTRAINT [PK_DEMO] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE SI2_VLAB
INSERT INTO DEMO VALUES(1,'Teste1')
INSERT INTO DEMO VALUES(2,'Teste2')
INSERT INTO DEMO VALUES(3,'Teste3')
INSERT INTO DEMO VALUES(4,'Teste4')
INSERT INTO DEMO VALUES(5,'Teste5')


