//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01_Basic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public int studentId { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateBirth { get; set; }
        public string sex { get; set; }
        public int country { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual Country OriginalCountry { get; set; }
    }
}
