--USE L51DG5--uncomment when using isel DB
BEGIN TRY  
BEGIN TRANSACTION 
    print 'Deleting and removing Tables'
    DROP TABLE IF EXISTS dbo.EMPLOYEE_SKILL;
    DROP TABLE IF EXISTS dbo.SKILL;
    DROP TABLE IF EXISTS dbo.SCHEDULING;
    DROP TABLE IF EXISTS dbo.NON_PERIODIC;
    DROP TABLE IF EXISTS dbo.PERIODIC;
    DROP TABLE IF EXISTS dbo.INTERVENTION;
    DROP TABLE IF EXISTS dbo.TEAM_MEMBER;
    DROP TABLE IF EXISTS dbo.MAINTENANCE_TEAM;
    DROP TABLE IF EXISTS dbo.REGISTER;
    DROP TABLE IF EXISTS dbo.ASSET;
    DROP TABLE IF EXISTS dbo.TYPE;
    DROP TABLE IF EXISTS dbo.EMPLOYEE;
 	COMMIT TRANSACTION
END TRY  

BEGIN CATCH
	ROLLBACK
	RAISERROR('Erro in removeTable', 16, 1)
END CATCH


