//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSET()
        {
            this.ASSET1 = new HashSet<ASSET>();
            this.INTERVENTIONs = new HashSet<INTERVENTION>();
            this.REGISTERs = new HashSet<REGISTER>();
        }
    
        public int id { get; set; }
        public string asset_name { get; set; }
        public System.DateTime acquisition_date { get; set; }
        public bool state { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public string location { get; set; }
        public Nullable<int> asset_reference { get; set; }
        public Nullable<int> manager { get; set; }
        public Nullable<int> type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSET> ASSET1 { get; set; }
        public virtual ASSET ASSET2 { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual TYPE TYPE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERVENTION> INTERVENTIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTER> REGISTERs { get; set; }
    }
}
