//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERVENTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INTERVENTION()
        {
            this.SCHEDULINGs = new HashSet<SCHEDULING>();
        }
    
        public int intervention_code { get; set; }
        public string description { get; set; }
        public string state { get; set; }
        public decimal price { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> asset_id { get; set; }
    
        public virtual ASSET ASSET { get; set; }
        public virtual NON_PERIODIC NON_PERIODIC { get; set; }
        public virtual PERIODIC PERIODIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCHEDULING> SCHEDULINGs { get; set; }
    }
}
