//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULING
    {
        public int team_code { get; set; }
        public int intervention_code { get; set; }
        public Nullable<System.DateTime> scheduling_date { get; set; }
    
        public virtual INTERVENTION INTERVENTION { get; set; }
        public virtual MAINTENANCE_TEAM MAINTENANCE_TEAM { get; set; }
    }
}
